# Generated by Django 4.2 on 2023-09-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Descricao', models.TextField()),
                ('Status', models.CharField(choices=[('fazendo', 'Fazendo'), ('feita', 'Feita')], max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
